import { DataInStore } from "./types";

export const mockData:  DataInStore = {
  students: {
    allIds: [
      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
      22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
    ],
    byId: {
      1: {
        id: 1,
        firstName: "Juliusz",
        lastName: "Słowacki",
        photo:
          "https://upload.wikimedia.org/wikipedia/commons/1/17/Juliusz_S%C5%82owacki_1.PNG",
        birthDate: 162297924000, // wartość w ms
        practiseInYears: 3,
        skills: [1, 4, 6, 7, 8, 10, 11], // tablica z kluczami/id umiejętności (np. skills.byId[1])
        projects: [1, 3, 5], // tablica z kluczami/id projektów (np. projects.byId[3])
        comments: [2, 5], // tablica z kluczami/id komentarzy (np. comments.byId[2])
      },
      2: {
        id: 2,
        firstName: "Rabindranath",
        lastName: "Tagore",
        photo:
          "https://cdn.pixabay.com/photo/2015/01/27/09/58/man-613601_960_720.jpg",
        birthDate: 424210912000,
        practiseInYears: 14,
        skills: [2, 4, 6, 9, 10, 12],
        projects: [2, 3, 6],
        comments: [1, 3],
      },
      3: {
        id: 3,
        firstName: "Olga",
        lastName: "Tokarczuk",
        photo:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Olga_Tokarczuk-9739.jpg/180px-Olga_Tokarczuk-9739.jpg",
        birthDate: 972906843000,
        practiseInYears: 1,
        skills: [1, 3, 4, 7, 9, 12],
        projects: [2, 4],
        comments: [1, 2, 4],
      },
      4: {
        id: 4,
        firstName: "Margaret",
        lastName: "Atwood",
        photo:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Margaret_Atwood_2015.jpg/160px-Margaret_Atwood_2015.jpg",
        birthDate: -19895817000,
        practiseInYears: 15,
        skills: [3, 4, 5, 6, 7, 9, 10, 11, 12],
        projects: [1, 2, 3, 4],
        comments: [1, 5],
      },
      5: {
        id: 5,
        firstName: "Zenek",
        lastName: "Słodowy",
        photo:
          "https://upload.wikimedia.org/wikipedia/commons/1/17/Juliusz_S%C5%82owacki_1.PNG",
        birthDate: 162297924000,
        practiseInYears: 3,
        skills: [1],
        projects: [1, 3, 5],
        comments: [2],
      },
      6: {
        id: 6,
        firstName: "Radek",
        lastName: "Zagórny",
        photo:
          "https://cdn.pixabay.com/photo/2015/01/27/09/58/man-613601_960_720.jpg",
        birthDate: 424210912000,
        practiseInYears: 14,
        skills: [2, 4, 6],
        projects: [2, 3, 6],
        comments: [1, 3],
      },
      7: {
        id: 7,
        firstName: "Tadeusz",
        lastName: "Tokar",
        photo:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Olga_Tokarczuk-9739.jpg/180px-Olga_Tokarczuk-9739.jpg",
        birthDate: 972906843000,
        practiseInYears: 1,
        skills: [1, 3],
        projects: [2, 4],
        comments: [1, 2, 4],
      },
      8: {
        id: 8,
        firstName: "Marcin",
        lastName: "Antoni",
        photo:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Margaret_Atwood_2015.jpg/160px-Margaret_Atwood_2015.jpg",
        birthDate: -19895817000,
        practiseInYears: 15,
        skills: [3, 5],
        projects: [1, 2, 3, 4],
        comments: [1, 5],
      },
      9: {
        id: 9,
        firstName: "Jan",
        lastName: "Nowaki",
        photo:
          "https://upload.wikimedia.org/wikipedia/commons/1/17/Juliusz_S%C5%82owacki_1.PNG",
        birthDate: 162297924000,
        practiseInYears: 3,
        skills: [1],
        projects: [1, 3, 5],
        comments: [2],
      },
      10: {
        id: 10,
        firstName: "Karol",
        lastName: "Tęgi",
        photo:
          "https://cdn.pixabay.com/photo/2015/01/27/09/58/man-613601_960_720.jpg",
        birthDate: 424210912000,
        practiseInYears: 14,
        skills: [2, 4, 6],
        projects: [2, 3, 6],
        comments: [1, 3],
      },
      11: {
        id: 11,
        firstName: "Wincent",
        lastName: "Biały",
        photo:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Olga_Tokarczuk-9739.jpg/180px-Olga_Tokarczuk-9739.jpg",
        birthDate: 972906843000,
        practiseInYears: 1,
        skills: [1, 3],
        projects: [2, 4],
        comments: [1, 2, 4],
      },
      12: {
        id: 12,
        firstName: "Rafał",
        lastName: "Góra",
        photo:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Margaret_Atwood_2015.jpg/160px-Margaret_Atwood_2015.jpg",
        birthDate: -19895817000,
        practiseInYears: 15,
        skills: [3, 5],
        projects: [1, 2, 3, 4],
        comments: [1, 5],
      },
      13: {
        id: 13,
        firstName: "Stefan",
        lastName: "Batory",
        photo:
          "https://upload.wikimedia.org/wikipedia/commons/1/17/Juliusz_S%C5%82owacki_1.PNG",
        birthDate: 162297924000,
        practiseInYears: 3,
        skills: [1],
        projects: [1, 3, 5],
        comments: [2],
      },
      14: {
        id: 14,
        firstName: "Sebastian",
        lastName: "Wczoraj",
        photo:
          "https://cdn.pixabay.com/photo/2015/01/27/09/58/man-613601_960_720.jpg",
        birthDate: 424210912000,
        practiseInYears: 14,
        skills: [2, 4, 6],
        projects: [2, 3, 6],
        comments: [1, 3],
      },
      15: {
        id: 15,
        firstName: "Wiktor",
        lastName: "Chmura",
        photo:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Olga_Tokarczuk-9739.jpg/180px-Olga_Tokarczuk-9739.jpg",
        birthDate: 972906843000,
        practiseInYears: 1,
        skills: [1, 3],
        projects: [2, 4],
        comments: [1, 2, 4],
      },
      16: {
        id: 16,
        firstName: "Grzegorz",
        lastName: "Tokarski",
        photo:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Margaret_Atwood_2015.jpg/160px-Margaret_Atwood_2015.jpg",
        birthDate: -19895817000,
        practiseInYears: 15,
        skills: [3, 5],
        projects: [1, 2, 3, 4],
        comments: [1, 5],
      },
      17: {
        id: 17,
        firstName: "Robert",
        lastName: "Stary",
        photo:
          "https://upload.wikimedia.org/wikipedia/commons/1/17/Juliusz_S%C5%82owacki_1.PNG",
        birthDate: 162297924000,
        practiseInYears: 3,
        skills: [1],
        projects: [1, 3, 5],
        comments: [2],
      },
      18: {
        id: 18,
        firstName: "Lukasz",
        lastName: "Niedzielan",
        photo:
          "https://cdn.pixabay.com/photo/2015/01/27/09/58/man-613601_960_720.jpg",
        birthDate: 424210912000,
        practiseInYears: 14,
        skills: [2, 4, 6],
        projects: [2, 3, 6],
        comments: [1, 3],
      },
      19: {
        id: 19,
        firstName: "Staefan",
        lastName: "Sosna",
        photo:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Olga_Tokarczuk-9739.jpg/180px-Olga_Tokarczuk-9739.jpg",
        birthDate: 972906843000,
        practiseInYears: 1,
        skills: [1, 3],
        projects: [2, 4],
        comments: [1, 2, 4],
      },
      20: {
        id: 20,
        firstName: "Monika",
        lastName: "Sabak",
        photo:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Margaret_Atwood_2015.jpg/160px-Margaret_Atwood_2015.jpg",
        birthDate: -19895817000,
        practiseInYears: 15,
        skills: [3, 5],
        projects: [1, 2, 3, 4],
        comments: [1, 5],
      },
      21: {
        id: 21,
        firstName: "Agnieszka",
        lastName: "Ryba",
        photo:
          "https://upload.wikimedia.org/wikipedia/commons/1/17/Juliusz_S%C5%82owacki_1.PNG",
        birthDate: 162297924000,
        practiseInYears: 3,
        skills: [1],
        projects: [1, 3, 5],
        comments: [2],
      },
      22: {
        id: 22,
        firstName: "Halina",
        lastName: "Serafin",
        photo:
          "https://cdn.pixabay.com/photo/2015/01/27/09/58/man-613601_960_720.jpg",
        birthDate: 424210912000,
        practiseInYears: 14,
        skills: [2, 4, 6],
        projects: [2, 3, 6],
        comments: [1, 3],
      },
      23: {
        id: 23,
        firstName: "Monika",
        lastName: "Tokarczuk",
        photo:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Olga_Tokarczuk-9739.jpg/180px-Olga_Tokarczuk-9739.jpg",
        birthDate: 972906843000,
        practiseInYears: 1,
        skills: [1, 3],
        projects: [2, 4],
        comments: [1, 2, 4],
      },
      24: {
        id: 24,
        firstName: "Radosław",
        lastName: "Sobota",
        photo:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Margaret_Atwood_2015.jpg/160px-Margaret_Atwood_2015.jpg",
        birthDate: -19895817000,
        practiseInYears: 15,
        skills: [3, 5],
        projects: [1, 2, 3, 4],
        comments: [1, 5],
      },
      25: {
        id: 25,
        firstName: "Jan",
        lastName: "Słowak",
        photo:
          "https://upload.wikimedia.org/wikipedia/commons/1/17/Juliusz_S%C5%82owacki_1.PNG",
        birthDate: 162297924000,
        practiseInYears: 3,
        skills: [1],
        projects: [1, 3, 5],
        comments: [2],
      },
      26: {
        id: 26,
        firstName: "Marta",
        lastName: "Kiwak",
        photo:
          "https://cdn.pixabay.com/photo/2015/01/27/09/58/man-613601_960_720.jpg",
        birthDate: 424210912000,
        practiseInYears: 14,
        skills: [2, 4, 6],
        projects: [2, 3, 6],
        comments: [1, 3],
      },
      27: {
        id: 27,
        firstName: "Renata",
        lastName: "Tobyla",
        photo:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Olga_Tokarczuk-9739.jpg/180px-Olga_Tokarczuk-9739.jpg",
        birthDate: 972906843000,
        practiseInYears: 1,
        skills: [1, 3],
        projects: [2, 4],
        comments: [1, 2, 4],
      },
      28: {
        id: 28,
        firstName: "Michał",
        lastName: "Atkinson",
        photo:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Margaret_Atwood_2015.jpg/160px-Margaret_Atwood_2015.jpg",
        birthDate: -19895817000,
        practiseInYears: 15,
        skills: [3, 5],
        projects: [1, 2, 3, 4],
        comments: [1, 5],
      },
      29: {
        id: 29,
        firstName: "Wojciech",
        lastName: "Młynarski",
        photo:
          "https://upload.wikimedia.org/wikipedia/commons/1/17/Juliusz_S%C5%82owacki_1.PNG",
        birthDate: 162297924000,
        practiseInYears: 3,
        skills: [1],
        projects: [1, 3, 5],
        comments: [2],
      },
      30: {
        id: 30,
        firstName: "Grażyna",
        lastName: "Targoska",
        photo:
          "https://cdn.pixabay.com/photo/2015/01/27/09/58/man-613601_960_720.jpg",
        birthDate: 424210912000,
        practiseInYears: 14,
        skills: [2, 4, 6],
        projects: [2, 3, 6],
        comments: [1, 3],
      },
      31: {
        id: 31,
        firstName: "Olek",
        lastName: "Tokarcz",
        photo:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Olga_Tokarczuk-9739.jpg/180px-Olga_Tokarczuk-9739.jpg",
        birthDate: 972906843000,
        practiseInYears: 1,
        skills: [1, 3],
        projects: [2, 4],
        comments: [1, 2, 4],
      },
      32: {
        id: 32,
        firstName: "Margo",
        lastName: "Smith",
        photo:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Margaret_Atwood_2015.jpg/160px-Margaret_Atwood_2015.jpg",
        birthDate: -19895817000,
        practiseInYears: 15,
        skills: [3, 5],
        projects: [1, 2, 3, 4],
        comments: [1, 5],
      },
    },
  },
  skills: {
    allIds: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    byId: {
      1: {
        id: 1,
        name: "JavaScript",
        rate: 4,
        category: 2, // id kategorii np. skills.categories[1]
      },
      2: {
        id: 2,
        name: "React",
        rate: "",
        category: 3,
      },
      3: {
        id: 3,
        name: "Vue",
        rate: 4,
        category: 3,
      },
      4: {
        id: 4,
        name: "Angular",
        rate: 5,
        category: 3,
      },
      5: {
        id: 5,
        name: "Python",
        rate: 2,
        category: 2,
      },
      6: {
        id: 6,
        name: "Git",
        rate: 3,
        category: 4,
      },
      7: {
        id: 7,
        name: "Webpack",
        rate: "",
        category: 4,
      },
      8: {
        id: 8,
        name: "Dobra organizacja pracy",
        rate: "",
        category: 1,
      },
      9: {
        id: 9,
        name: "Komunikatywność",
        rate: 4,
        category: 1,
      },
      10: {
        id: 10,
        name: "Umiejętność pracy w zespole",
        rate: 4,
        category: 1,
      },
      11: {
        id: 11,
        name: "Heroku",
        rate: "",
        category: 4,
      },
      12: {
        id: 12,
        name: "Java",
        rate: "",
        category: 2,
      },
    },
    categories: {
      allIds: [1, 2, 3, 4],

      byId: {
        1: {
          id: 1,
          name: "soft",
        },
        2: {
          id: 2,
          name: "languages",
        },
        3: {
          id: 3,
          name: "frameworks",
        },
        4: {
          id: 4,
          name: "tools",
        },
      },
    },
  },
  projects: {
    allIds: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
    byId: {
      1: {
        id: 1,
        name: "Ekran główny",
        company: "Orlen",
        from: 1573383600000,
        to: 1607598000000,
        status: 0,
      },
      2: {
        id: 2,
        name: "Implementacja bazy danych",
        company: "Statoil",
        from: undefined,
        to: undefined,
        status: 0,
      },
      3: {
        id: 3,
        name: "Aplikacja zakupowa dla firm",
        company: "Shell",
        from: 1615978800000,
        to: undefined,
        status: 1,
      },
      4: {
        id: 4,
        name: "Panel do zarządzania stacją benzynową",
        company: "Exon Mobil",
        from: 1523613600000,
        to: 1546167600000,
        status: 0,
      },
      5: {
        id: 5,
        name: "Aplkacja kadrowo-księgowa",
        company: "Orlen",
        from: 1621687532000,
        to: undefined,
        status: 2,
      },
      6: {
        id: 6,
        name: "Strona do akcji promocyjnej 'Tankuj do pełna!'",
        company: "Shell",
        from: 1628772332000,
        to: undefined,
        status: 2,
      },
      7: {
        id: 7,
        name: "segtsrewgt główny",
        company: "Orresgtedsrlen",
        from: 1573383600000,
        to: 1607598000000,
        status: 1,
      },

      8: {
        id: 8,
        name: "8 główny",
        company: "Orresgtedsrlen",
        from: 1573383600000,
        to: 1607598000000,
        status: 1,
      },
      9: {
        id: 9,
        name: "9 główny",
        company: "Orresgtedsrlen",
        from: 1573383600000,
        to: 1607598000000,
        status: 1,
      },
      10: {
        id: 10,
        name: "10 główny",
        company: "Orlen",
        from: 1573383600000,
        to: 1607598000000,
        status: 1,
      },
      11: {
        id: 11,
        name: "11 bazy danych",
        company: "Statoil",
        from: undefined,
        to: undefined,
        status: 1,
      },
      12: {
        id: 12,
        name: "12 zakupowa dla firm",
        company: "Shell",
        from: 1615978800000,
        to: undefined,
        status: 1,
      },
      13: {
        id: 13,
        name: "13 do zarządzania stacją benzynową",
        company: "Exon Mobil",
        from: 1523613600000,
        to: 1546167600000,
        status: 1,
      },
      14: {
        id: 14,
        name: "14 kadrowo-księgowa",
        company: "Orlen",
        from: 1621687532000,
        to: undefined,
        status: 1,
      },
      15: {
        id: 15,
        name: "16 do akcji promocyjnej 'Tankuj do pełna!'",
        company: "Shell",
        from: 1628772332000,
        to: undefined,
        status: 1,
      },
      16: {
        id: 16,
        name: "16 do akcji promocyjnej 'Tankuj do pełna!'",
        company: "Shell",
        from: 1628772332000,
        to: undefined,
        status: 1,
      },
      17: {
        id: 17,
        name: "17 główny",
        company: "Orresgtedsrlen",
        from: 1573383600000,
        to: 1607598000000,
        status: 1,
      },

      18: {
        id: 18,
        name: "18 główny",
        company: "Orresgtedsrlen",
        from: 1573383600000,
        to: 1607598000000,
        status: 1,
      },
      19: {
        id: 19,
        name: "19 główny",
        company: "Orresgtedsrlen",
        from: 1573383600000,
        to: 1607598000000,
        status: 1,
      },
    },
    statuses: [
      { id: 0, name: "Zaplanowany" },
      { id: 1, name: "W toku" },
      { id: 2, name: "Zamknięty" },
    ],
  },
  comments: {
    allIds: [1, 2, 3, 4, 5],
    byId: {
      1: {
        id: 1,
        author: "Zawisza Czarny",
        text: "Aenean nonummy enim vel odio neque, quis nisl. Sed sagittis, nunc mauris, consectetuer tincidunt et, tincidunt justo. Donec nec velit magna, tincidunt nonummy, tellus enim, ac elit tincidunt mi, quis wisi. Aenean ac quam nunc, dapibus augue odio at tortor. In vehicula lectus.",
      },
      2: {
        id: 2,
        author: "Król Artur",
        text: "Już nie zaś teorię, okazuje się iż zakończenie tego projektu spełnia ważne zadanie w restrukturyzacji przedsiębiorstwa. Wagi i określenia systemu powoduje docenianie wag modelu rozwoju. Już nie zaś teorię, okazuje się iż zakończenie tego projektu spełnia ważne zadanie w restrukturyzacji przedsiębiorstwa. Wagi i określenia systemu powoduje docenianie wag modelu rozwoju.Już nie zaś teorię, okazuje się iż zakończenie tego projektu spełnia ważne zadanie w restrukturyzacji przedsiębiorstwa. Wagi i określenia systemu powoduje docenianie wag modelu rozwoju",
      },
      3: {
        id: 3,
        author: "Maćko z Bogdańca",
        text: "Wszystko bieży ku drzwiom odprowadzał i Suwarów w polskiej szacie siedzi Rejtan żałośny po łacinie. Mężczyznom dano wódkę. wtenczas wszyscy siedli i ma albo sam przyjmować i na Francuza. ",
      },
      4: {
        id: 4,
        author: "Jan bez Ziemi",
        text: "Przypominam też do czynienia dobrego uznał, a wszakże Dobro jest zbiorem przedmiotów doświadczenia.",
      },
      5: {
        id: 5,
        author: "Gall Anonim",
        text: "Curabitur tempor. Suspendisse commodo wisi. Nam varius in, mauris. Etiam malesuada neque quis ante. Quisque ultricies",
      },
    },
  },
};
